// frontend-react/src/features/customers/components/CustomerForm.tsx
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/Button';
import { FormRootError, SelectField, TextArea, TextField } from '@/components/FormField';
import { applyServerErrors } from '@/lib/apiErrors';
import { customerFormSchema, emptyCustomerForm, toApiPayload, type CustomerFormValues } from '../schema';
import type { Customer } from '../types';
import { GENDERS } from '../types';

interface Props {
  initialValues?: Customer;
  /** Sent the `CustomerCreate` / `CustomerUpdate` payload. */
  onSubmit: (payload: Record<string, unknown>) => Promise<Customer>;
  /** Called on success with the saved customer. */
  onSaved?: (c: Customer) => void;
  /** Where to return on cancel. */
  cancelTo: string;
  submitLabel?: string;
}

export function CustomerForm({ initialValues, onSubmit, onSaved, cancelTo, submitLabel = 'Save' }: Props) {
  const navigate = useNavigate();
  const {
    register,
    handleSubmit,
    setError,
    formState: { errors, isSubmitting },
  } = useForm<CustomerFormValues>({
    resolver: zodResolver(customerFormSchema),
    defaultValues: initialValues ? toFormValues(initialValues) : emptyCustomerForm,
  });

  async function submit(values: CustomerFormValues) {
    try {
      const payload = toApiPayload(values);
      const saved = await onSubmit(payload);
      onSaved?.(saved);
    } catch (err) {
      applyServerErrors<CustomerFormValues>(err, setError, {
        fallbackMessage: 'Failed to save customer. Please try again.',
      });
    }
  }

  return (
    <form onSubmit={handleSubmit(submit)} className="flex flex-col gap-6" noValidate>
      <FormRootError message={errors.root?.serverError?.message as string | undefined} />

      <section aria-label="Personal details" className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <TextField
          label="Full name"
          required
          autoComplete="name"
          error={errors.name?.message}
          {...register('name')}
        />
        <TextField
          label="Email"
          type="email"
          autoComplete="email"
          error={errors.email?.message}
          {...register('email')}
        />
        <TextField
          label="Phone"
          autoComplete="tel"
          error={errors.phone?.message}
          {...register('phone')}
        />
        <SelectField
          label="Gender"
          error={errors.gender?.message}
          defaultValue=""
          {...register('gender')}
        >
          <option value="">—</option>
          {GENDERS.map((g) => (
            <option key={g} value={g}>
              {g.charAt(0).toUpperCase() + g.slice(1)}
            </option>
          ))}
        </SelectField>
        <TextField
          label="Date of birth"
          type="date"
          error={errors.date_of_birth?.message}
          {...register('date_of_birth')}
        />
        <TextField
          label="Birth time"
          type="time"
          error={errors.birth_time?.message}
          {...register('birth_time')}
        />
        <TextField
          label="Birth place"
          error={errors.birth_place?.message}
          {...register('birth_place')}
        />
        <TextField
          label="Occupation"
          error={errors.occupation?.message}
          {...register('occupation')}
        />
        <TextField
          label="Marital status"
          error={errors.marital_status?.message}
          {...register('marital_status')}
        />
      </section>

      <section aria-label="Address" className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <TextArea
          label="Address"
          rows={2}
          className="sm:col-span-2"
          error={errors.address?.message}
          {...register('address')}
        />
        <TextField label="City" error={errors.city?.message} {...register('city')} />
        <TextField label="State" error={errors.state?.message} {...register('state')} />
        <TextField label="Pincode" error={errors.pincode?.message} {...register('pincode')} />
      </section>

      <section aria-label="Astrological" className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <TextField label="Rashi" error={errors.rashi?.message} {...register('rashi')} />
        <TextField label="Nakshatra" error={errors.nakshatra?.message} {...register('nakshatra')} />
        <TextField label="Gotra" error={errors.gotra?.message} {...register('gotra')} />
        <TextField label="Lagna" error={errors.lagna?.message} {...register('lagna')} />
      </section>

      <section>
        <TextArea label="Notes" rows={4} error={errors.notes?.message} {...register('notes')} />
      </section>

      <div className="flex items-center justify-end gap-2">
        <Button type="button" variant="secondary" onClick={() => navigate(cancelTo)}>
          Cancel
        </Button>
        <Button type="submit" variant="primary" disabled={isSubmitting}>
          {isSubmitting ? 'Saving…' : submitLabel}
        </Button>
      </div>
    </form>
  );
}

function toFormValues(c: Customer): CustomerFormValues {
  return {
    name: c.name ?? '',
    email: c.email ?? '',
    phone: c.phone ?? '',
    gender: (c.gender as string | null) ?? '',
    date_of_birth: c.date_of_birth ?? '',
    birth_time: c.birth_time ?? '',
    birth_place: c.birth_place ?? '',
    occupation: c.occupation ?? '',
    marital_status: c.marital_status ?? '',
    address: c.address ?? '',
    city: c.city ?? '',
    state: c.state ?? '',
    pincode: c.pincode ?? '',
    rashi: c.rashi ?? '',
    nakshatra: c.nakshatra ?? '',
    gotra: c.gotra ?? '',
    lagna: c.lagna ?? '',
    notes: c.notes ?? '',
  };
}

// frontend/src/views/CustomerForm.vue
<template>
  <div>
    <h1 class="text-2xl font-bold mb-6">{{ isEdit ? 'Edit Customer' : 'New Customer' }}</h1>

    <form @submit.prevent="handleSubmit" class="space-y-6 max-w-3xl">
      <div class="bg-white rounded-xl border p-5">
        <h3 class="font-semibold text-gray-700 mb-4">Personal Info</h3>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label class="block text-xs font-medium text-gray-600 mb-1">Name *</label>
            <input v-model="form.name" required class="form-input" />
          </div>
          <div>
            <label class="block text-xs font-medium text-gray-600 mb-1">Email</label>
            <input v-model="form.email" type="email" class="form-input" />
          </div>
          <div>
            <label class="block text-xs font-medium text-gray-600 mb-1">Phone</label>
            <input v-model="form.phone" class="form-input" />
          </div>
          <div>
            <label class="block text-xs font-medium text-gray-600 mb-1">Gender</label>
            <select v-model="form.gender" class="form-select w-full">
              <option value="">—</option>
              <option value="male">male</option>
              <option value="female">female</option>
              <option value="other">other</option>
            </select>
          </div>
          <div>
            <label class="block text-xs font-medium text-gray-600 mb-1">Date of Birth</label>
            <input v-model="form.date_of_birth" type="date" class="form-input" />
          </div>
          <div>
            <label class="block text-xs font-medium text-gray-600 mb-1">Birth Time</label>
            <input v-model="form.birth_time" type="time" class="form-input" />
          </div>
          <div>
            <label class="block text-xs font-medium text-gray-600 mb-1">Birth Place</label>
            <input v-model="form.birth_place" class="form-input" />
          </div>
          <div>
            <label class="block text-xs font-medium text-gray-600 mb-1">Occupation</label>
            <input v-model="form.occupation" class="form-input" />
          </div>
          <div>
            <label class="block text-xs font-medium text-gray-600 mb-1">Marital Status</label>
            <input v-model="form.marital_status" class="form-input" />
          </div>
        </div>
      </div>

      <div class="bg-white rounded-xl border p-5">
        <h3 class="font-semibold text-gray-700 mb-4">Address</h3>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div class="md:col-span-2">
            <label class="block text-xs font-medium text-gray-600 mb-1">Address</label>
            <input v-model="form.address" class="form-input" />
          </div>
          <div>
            <label class="block text-xs font-medium text-gray-600 mb-1">City</label>
            <input v-model="form.city" class="form-input" />
          </div>
          <div>
            <label class="block text-xs font-medium text-gray-600 mb-1">State</label>
            <input v-model="form.state" class="form-input" />
          </div>
          <div>
            <label class="block text-xs font-medium text-gray-600 mb-1">Pincode</label>
            <input v-model="form.pincode" class="form-input" />
          </div>
        </div>
      </div>

      <div class="bg-white rounded-xl border p-5">
        <h3 class="font-semibold text-gray-700 mb-4">Astrology</h3>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label class="block text-xs font-medium text-gray-600 mb-1">Rashi</label>
            <input v-model="form.rashi" class="form-input" />
          </div>
          <div>
            <label class="block text-xs font-medium text-gray-600 mb-1">Nakshatra</label>
            <input v-model="form.nakshatra" class="form-input" />
          </div>
          <div>
            <label class="block text-xs font-medium text-gray-600 mb-1">Gotra</label>
            <input v-model="form.gotra" class="form-input" />
          </div>
          <div>
            <label class="block text-xs font-medium text-gray-600 mb-1">Lagna</label>
            <input v-model="form.lagna" class="form-input" />
          </div>
        </div>
      </div>

      <div class="bg-white rounded-xl border p-5">
        <h3 class="font-semibold text-gray-700 mb-4">Notes</h3>
        <textarea v-model="form.notes" rows="3"
          class="form-input"></textarea>
      </div>

      <div class="flex gap-3">
        <button type="submit" :disabled="saving"
          class="btn-primary px-6">
          {{ saving ? 'Saving...' : (isEdit ? 'Update' : 'Create') }}
        </button>
        <button type="button" @click="$router.back()"
          class="btn-secondary px-6">Cancel</button>
      </div>
    </form>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { createCustomer, getCustomer, updateCustomer } from '@/api/customers'

const route = useRoute()
const router = useRouter()
const props = defineProps({ id: String })
const customerId = props.id || route.params.id
const isEdit = computed(() => !!customerId)
const saving = ref(false)

const form = ref({
  name: '', email: '', phone: '', gender: '', date_of_birth: '', birth_time: '',
  birth_place: '', occupation: '', marital_status: '',
  address: '', city: '', state: '', pincode: '',
  rashi: '', nakshatra: '', gotra: '', lagna: '', notes: '',
})

async function handleSubmit() {
  saving.value = true
  // Remove empty string values
  const payload = {}
  for (const [k, v] of Object.entries(form.value)) {
    if (v !== '' && v != null) payload[k] = v
  }
  try {
    if (isEdit.value) {
      await updateCustomer(customerId, payload)
    } else {
      await createCustomer(payload)
    }
    router.push(isEdit.value ? `/customers/${customerId}` : '/customers')
  } finally {
    saving.value = false
  }
}

onMounted(async () => {
  if (isEdit.value) {
    const { data } = await getCustomer(customerId)
    Object.keys(form.value).forEach((k) => {
      if (data[k] != null) form.value[k] = data[k]
    })
  }
})
</script>
